"use client";
import Header from "@/components/Header";
import Script from "next/script";
import { DataContextProvider } from "../contexts/dataContext";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dollarcostaverage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <DataContextProvider>
   
      <html lang="en">
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css"
          rel="stylesheet"
        />
          <Script
          src="https://kit.fontawesome.com/78485b5ada.js"
          crossOrigin="anonymous"
        ></Script>
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"></Script>

        <body>
          <Header />
          <NavBar />
          {children}
        </body>
      </html>
    </DataContextProvider>
  );
}
